name: therealslimdyer
favicon: null
layout_spectrum: 0.24608968710526824
typography_spectrum: 0.8381872605532408
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0f0e09'
    - '#838266'
    - '#f5c98d'
    - '#aab536'
  brandStrength: 0.5
  lightness: 0.5983415420632809
  saturation: 0.5625
  rhythmicContrast: 0.6467496789991856
purpose: []
